app/Http/Controllers/ClxMessagesController.php, app/Models/ClxMessage.php, database/migrations/2022_07_06_234730_add_d_l_messages_to_clx_messages.php, resources/views/controllers/clx/rcl-messages/show.blade.php, resources/views/livewire/pilots/message-history.blade.php
https://github.com/czqoocavatsim/nattrakv1/issues/13
=> 13 CLX: ATC SPEED CHANGE based off previous CLX not original RCL

app/Models/RclMessage.php, resources/views/controllers/clx/processed.blade.php, resources/views/controllers/clx/rcl-messages/show.blade.php
https://github.com/czqoocavatsim/nattrakv1/issues/11
=> 11 RLX:  FL/Mach shown is the requested FL/Mach - not the cleared FL/Mach

app/Http/Controllers/ClxMessagesController.php, app/Http/Controllers/RclMessagesController.php, app/Http/Requests/RclMessageRequest.php, app/Models/ClxMessage.php, app/Models/RclMessage.php, app/Models/Track.php, database/migrations/2022_07_07_003020_add_concorde_tracks_to_tracks.php, database/migrations/2022_07_07_011729_add_concorde_columns.php, resources/views/controllers/clx/processed.blade.php, resources/views/controllers/clx/rcl-messages/show.blade.php, resources/views/livewire/controllers/pending-rcl-messages.blade.php, resources/views/pilots/rcl/create.blade.php
https://github.com/czqoocavatsim/nattrakv1/issues/5
=> 5 Allow for Concorde RCL request

app/Enums/ConflictLevelEnum.php, app/Http/Controllers/ClxMessagesController.php, app/Http/Livewire/Controllers/ConflictChecker.php, app/Models/ClxMessage.php, app/Models/RclMessage.php, app/Models/Track.php, app/Models/VatsimAccount.php, database/migrations/2023_03_20_195624_add_raw_entry_time_to_clx_messages.php, resources/js/app.js, resources/views/_layouts/main.blade.php, resources/views/controllers/clx/rcl-messages/show.blade.php, resources/views/livewire/controllers/conflict-checker.blade.php
=> Conflict detection when editing RCL

Dockerfile
Discovered in prod that we weren't building frontend assets.
=> Build frontend assets into docker image

app/Console/Commands/ClearLockedRclMessagesCommand.php, app/Console/Kernel.php
=> Add unlock command and task scheduler event

Dockerfile
=> Build livewire assets into container image

resources/views/pilots/rcl/create.blade.php
=> Pilot RCL create UI auto selects entry fix if track selected

app/Http/Controllers/Api/PluginDataController.php
Grab the data we need at query time
=> Optimize api eloquent queries

app/Http/Controllers/ClxMessagesController.php, app/Http/Livewire/Controllers/PendingRclMessages.php, app/Http/Requests/ClxMessageRequest.php, app/Models/ClxMessage.php, database/migrations/2023_04_25_171114_duplicate_is_concorde_to_clx_messages.php, resources/views/controllers/clx/pending.blade.php, resources/views/controllers/clx/processed.blade.php, resources/views/controllers/clx/rcl-messages/show.blade.php, resources/views/pilots/rcl/create.blade.php
There is an issue where you literally cannot see the Concorde tracks on the controller side (and therefore the RCL messages), and even then can't change the clearance block level.
=> Concordes block reclearances, track sorting

app/Console/Commands/PopulateTracksCommand.php, app/Helpers.php, app/Models/Bulletin.php, app/Models/ClxMessage.php, app/Models/CpdlcMessage.php, app/Models/RclMessage.php, app/Models/Track.php, app/Models/VatsimAccount.php, database/migrations/2023_08_31_161419_add_flight_levels_to_tracks.php, resources/views/tracks/index.blade.php
=> Add flight levels to tracks page

app/Http/Controllers/AdministrationController.php, resources/views/_layouts/main.blade.php, resources/views/administration/utility.blade.php, routes/web.php
=> Add clear database function

app/Http/Controllers/RclMessagesController.php, app/Models/RclMessage.php, database/migrations/2023_10_12_113458_add_re_request_to_rcl_messages.php, resources/views/controllers/clx/rcl-messages/show.blade.php, resources/views/pilots/nav.blade.php, resources/views/pilots/rcl/index.blade.php, routes/web.php, vite.config.js
https://github.com/vatsimnetwork/nattrak/issues/91
=> 91 RCL re-request 

.github/workflows/docker.yml, Dockerfile
=> Pass Vite envvars through to image build

app/Http/Controllers/Api/PluginDataController.php
Caching data returned by `/api/plugins` for 60 seconds.
Also, some random code cleanup.
=> Cache RclMessages API

app/Http/Requests/RclMessageRequest.php
https://github.com/vatsimnetwork/nattrak/issues/101
=> 101 Fix RCL time constraints

resources/views/welcome.blade.php
https://github.com/vatsimnetwork/nattrak/issues/105
=> 105 Add message when logged in but not connected as pilot

app/Http/Requests/RclMessageRequest.php
https://github.com/vatsimnetwork/nattrak/issues/102
=> 102 Two digit minute could not be found (RCL validation)

app/Http/Livewire/Pilots/NotifyNewEta.php
https://github.com/vatsimnetwork/nattrak/issues/111
=> 111 Notify new ETA error when no previous CLX

app/Http/Controllers/Api/PluginDataController.php, app/Http/Livewire/Controllers/PgClxMessages.php, app/Http/Livewire/Controllers/PgPendingRclMessages.php
=> Improve some queries by eager-loading relations

app/Services/VatsimDataService.php
=> Cache network data in request so we only hit redis once

app/Services/VatsimDataService.php
=> Null-safe check, derp

app/Console/Commands/PopulateTracksCommand.php, app/Helpers.php, app/Services/TracksService.php, app/Services/VatsimDataService.php
=> new nat parsing code, discontinue use of gander api

app/Enums/DomesticAuthorities.php, app/Http/Livewire/Controllers/NotifyNewEtaForPilot.php, app/Providers/AuthServiceProvider.php, app/Services/VatsimDataService.php, resources/views/_layouts/main.blade.php, resources/views/controllers/nav.blade.php, resources/views/controllers/notify-new-eta-for-pilot.blade.php, resources/views/livewire/controllers/notify-new-eta-for-pilot.blade.php, routes/web.php
A new "DomesticAuthorities" enum provides for the logon prefixes that will allow access to the functionality.
=> Allow for ATC to notify new ETA for pilots

app/Http/Controllers/ClxMessagesController.php, app/Http/Livewire/Controllers/LtNewPending.php, app/Http/Livewire/Controllers/LtNewProcessed.php, app/Models/RclMessage.php, routes/web.php
=> QOL improvements CTP 24E

app/Http/Livewire/Controllers/LtNewPending.php, app/Http/Livewire/Controllers/LtNewProcessed.php
Fixes dd084d49ffc843ab82eaebf11d739641
=> Hotfix 1.8.3a

app/Http/Controllers/DatalinkAuthorityController.php, app/Http/Livewire/Administration/CreateDatalinkAuthority.php, app/Http/Livewire/Administration/DatalinkAuthoritiesTable.php, app/Http/Requests/DatalinkAuthorityRequest.php, app/Models/DatalinkAuthority.php, app/Policies/DatalinkAuthorityPolicy.php, app/Providers/AuthServiceProvider.php, database/migrations/2024_10_20_124639_create_datalink_authorities_table.php, database/seeders/DatalinkAuthoritiesSeeder.php, resources/views/_layouts/main.blade.php, resources/views/administration/datalink_authorities.blade.php, resources/views/livewire/administration/create-datalink-authority.blade.php, routes/web.php
Required for datalink authorities to have different settings to accomodate Gander/Shanwick prior to 4 December
=> Move datalink authorities to database

resources/views/livewire/controllers/create-manual-clx.blade.php
Incorrect/Duplicated point at pending view instead of processed
=> Correct processed return on manual CLX

app/Services/TracksService.php, config/services.php
=> feat(tracks): Change FAA URL, make configurable

app/Services/TracksService.php
Time to play some games, FAA/Akamai...
=> fix(tracks): Use non-bot user agent
